---
kind: pipeline
type: docker
name: default1

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: Nitwel/playcah
    tags:
    - latest
