export const cardDecks = [
    { name: 'Base Set', value: 'Base' },
    { name: 'The First Expansion', value: 'CAHe1' },
    { name: 'The Second Expansion', value: 'CAHe2' },
    { name: 'The Third Expansion', value: 'CAHe3' },
    { name: 'The Fourth Expansion', value: 'CAHe4' },
    { name: 'The Fifth Expansion', value: 'CAHe5' },
    { name: 'The Sixth Expansion', value: 'CAHe6' },
    { name: 'Green Box Expansion', value: 'greenbox' },
    { name: '90s Nostalgia Pack', value: '90s' },
    { name: 'Box Expansion', value: 'Box' },
    { name: 'Fantasy Pack', value: 'fantasy' },
    { name: 'Food Pack', value: 'food' },
    { name: 'Science Pack', value: 'science' },
    { name: 'World Wide Web Pack', value: 'www' },
    { name: 'Vote for Hillary Pack', value: 'hillary' },
    { name: 'Vote for Trump Pack', value: 'trumpvote' },
    { name: 'Trump Survival Pack', value: 'trumpbag' },
    { name: '2012 Holiday Pack', value: 'xmas2012' },
    { name: '2013 Holiday Pack', value: 'xmas2013' },
    { name: 'PAX East 2013', value: 'PAXE2013' },
    { name: 'PAX Prime 2013', value: 'PAXP2013' },
    { name: 'PAX East 2014', value: 'PAXE2014' },
    { name: 'PAX East 2014 Panel Pack', value: 'PAXEP2014' },
    { name: 'PAX Prime 2014 Panel Pack', value: 'PAXPP2014' },
    { name: 'PAX Prime 2015 Food Packs', value: 'PAX2015' },
    { name: 'House of Cards Against Humanity', value: 'HOCAH' },
    { name: 'Reject Pack', value: 'reject' },
    { name: 'Reject Pack 2', value: 'reject2' },
    { name: 'Canadian', value: 'Canadian' },
    { name: 'Misprint Replacement Bonus Cards', value: 'misprint' },
    { name: 'UoP Pack', value: 'uop' },
    { name: '[$] Apples to Apples&reg; Party Pack', value: 'apples' },
    { name: '[$] Crabs Adjust Humidity', value: 'crabs' },
    { name: '[$] Cads About Matrimony', value: 'matrimony' },
    { name: '[C] /tg/', value: 'c-tg' },
    { name: '[C] Admin\'s Picks', value: 'c-admin' },
    { name: '[C] Anime', value: 'c-anime' },
    { name: '[C] Antisocial Injustice', value: 'c-antisocial' },
    { name: '[C] Cards Against Equinity', value: 'c-equinity' },
    { name: '[C] Cards Against Homestuck', value: 'c-homestuck' },
    { name: '[C] Derps Against Humanity', value: 'c-derps' },
    { name: '[C] Doctor Who', value: 'c-doctorwho' },
    { name: '[C] Eurovision Song Contest', value: 'c-eurovision' },
    { name: '[C] FiMFiction.net', value: 'c-fim' },
    { name: '[C] Game Grumps', value: 'c-gamegrumps' },
    { name: '[C] Golby Fan Club', value: 'c-golby' },
    { name: '[C] Game of Thrones (no spoilers)', value: 'GOT' },
    { name: '[C] Grognards Against Humanity (RPG fandom pack)', value: 'CAHgrognards' },
    { name: '[C] Hackers Against Humanity', value: 'HACK' },
    { name: '[C] Joey Image 1', value: 'Image1' },
    { name: '[C] Ladies Against Humanity', value: 'c-ladies' },
    { name: '[C] Imgur', value: 'c-imgur' },
    { name: '[C] Khaos WolfKat', value: 'c-khaos' },
    { name: '[C] Mr. Man Collection', value: 'c-mrman' },
    { name: '[C] NEIndy', value: 'c-neindy' },
    { name: '[C] Nobilis Reed', value: 'c-nobilis' },
    { name: '[C] Not Safe For Humanity', value: 'NSFH' },
    { name: '[C] Northernlion', value: 'c-northernlion' },
    { name: '[C] RagingPsyfag\'s Pack of Shenanigans', value: 'c-ragingpsyfag' },
    { name: '[C] Ridiculously Stupid', value: 'c-stupid' },
    { name: '[C] Rooster Teeth', value: 'c-rt' },
    { name: '[C] RPAnons', value: 'c-rpanons' },
    { name: '[C] SocialGamer', value: 'c-socialgamer' },
    { name: '[C] Sodomy Dog\'s Furry Pack', value: 'c-sodomydog' },
    { name: '[C] That Guy With The Glasses', value: 'c-guywglasses' },
    { name: '[C] Very Serious', value: 'c-vewysewious' },
    { name: '[C] Vidya', value: 'c-vidya' },
    { name: '[C] xkcd', value: 'c-xkcd' }
]